// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const findOrCreateUser = `-- name: FindOrCreateUser :one
INSERT INTO users (firebase_uid, provider, email, name, picture)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (firebase_uid) DO UPDATE
  SET provider = EXCLUDED.provider,
      email = EXCLUDED.email,
      name = EXCLUDED.name,
      picture = EXCLUDED.picture
RETURNING id, firebase_uid, provider, email, name, picture, created_at
`

type FindOrCreateUserParams struct {
	FirebaseUID string         `json:"firebase_uid"`
	Provider    string         `json:"provider"`
	Email       string         `json:"email"`
	Name        sql.NullString `json:"name"`
	Picture     sql.NullString `json:"picture"`
}

func (q *Queries) FindOrCreateUser(ctx context.Context, arg FindOrCreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, findOrCreateUser,
		arg.FirebaseUID,
		arg.Provider,
		arg.Email,
		arg.Name,
		arg.Picture,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUID,
		&i.Provider,
		&i.Email,
		&i.Name,
		&i.Picture,
		&i.CreatedAt,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, firebase_uid, provider, email, name, picture, created_at FROM users WHERE id = $1
`

func (q *Queries) FindUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUID,
		&i.Provider,
		&i.Email,
		&i.Name,
		&i.Picture,
		&i.CreatedAt,
	)
	return i, err
}
